index:
    path: /
    controller: App\Controller\PageController::index

fos_user.registration:
    path: /register
    defaults:
        _controller: App\Controller\RegistrationController::registerAction
